# Install script for directory: /home/zeus/projects/pong-source

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "DEBUG")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/bin" TYPE PROGRAM FILES "/home/zeus/projects/pong-source/Debug/pong-launcher")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default" TYPE FILE FILES
    "/home/zeus/projects/pong-source/VERSION"
    "/home/zeus/projects/pong-source/LICENSE"
    "/home/zeus/projects/pong-source/README"
    "/home/zeus/projects/pong-source/DEBIAN"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default" TYPE FILE FILES "/home/zeus/projects/pong-source/app.yaml")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources" TYPE FILE FILES "/home/zeus/projects/pong-source/Debug/resources/.stamp")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/manifests" TYPE FILE RENAME "MANIFEST.json" FILES "/home/zeus/projects/pong-source/src/MANIFEST.json")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources" TYPE DIRECTORY FILES "/home/zeus/projects/pong-source/game_data")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources/game_data" TYPE FILE FILES "/home/zeus/projects/pong-source/Debug/resources/.stamp")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources" TYPE DIRECTORY FILES "/home/zeus/projects/pong-source/client_data")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources/client_data" TYPE FILE FILES "/home/zeus/projects/pong-source/Debug/resources/.stamp")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources" TYPE DIRECTORY FILES "/home/zeus/projects/pong-source/src/json_protocols")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/usr/share/pong/default/resources/json_protocols" TYPE FILE FILES "/home/zeus/projects/pong-source/Debug/resources/.stamp")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "default")

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/zeus/projects/pong-source/Debug/src/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/home/zeus/projects/pong-source/Debug/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/home/zeus/projects/pong-source/Debug/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
