#!/bin/bash -e
# vim: fileencoding=utf-8 tabstop=2 softtabstop=2 shiftwidth=2 expandtab

# This file has been generated and can be overwritten by the make command.
# Please use environment variables rather than directly editing this script
# to override variables.

################################################################################
# ENVRIONMENT VARIABLES THAT YOU CAN OVERRIDE:
#
#   MALLOC_ANREA_TEST       : Malloc-related variable.
#                           : Default: 1
#   MALLOC_ANREA_MAX        : Malloc-related variable.
#                           : Default: 1
#   GAME_ROOT_DIR           : Specifies where you unpacked your package.
#                             Default: /
#   GAME_MANIFEST_OVERRIDE  : Specifies overriding MANIFEST.json.
#                             Default: /etc/pong/MANIFEST.override.json
#   GAME_LOG_ROOT_DIR       : Specifies where you wnat to gnenerate log files.
#                             Default: /home/zeus/projects/pong-source/Debug/logs
#   GAME_CRASHDUMP_ROOT_DIR : Specifies where you wnat to generate dump files.
#                             Default: /home/zeus/projects/pong-source/Debug/dumps
#   GAME_GLOG_OPTIONS       : Specifies additinal Google glot options.
#                             Default: --max_log_size=10 --alsologtostderr --stop_logging_if_full_disk
#   GAME_CONTACT_EMAIL_ADDRESS : Specifies email address to receive alert emails.
#                             Default: 
#
# You can override by using 'export VAR="value"' before running this script.
# If you are running the script through upstart or systemd, set the variable
#   in /etc/default/<your_game_name>.
################################################################################
export MALLOC_ARENA_TEST=${MALLOC_ARENA_TEST:-1}
export MALLOC_ARENA_MAX=${MALLOC_ARENA_MAX:-1}


################################################################################
# FUNAPI LOCATION.
################################################################################
export FUNAPI_ROOT="/usr"
export FUNAPI_BIN_DIR="$FUNAPI_ROOT/bin"
export FUNAPI_DATA_DIR="$FUNAPI_ROOT/share/funapi"


################################################################################
# YOUR GAME INFO.
################################################################################
component_name="pong_server"
ComponentName="PongServer"
COMPONENT_NAME="PONG_SERVER"
flavor_name="default"


################################################################################
# YOUR GAME LOCATIONS.
################################################################################
debugging_symbol_dir="$GAME_ROOT_DIR/home/zeus/projects/pong-source/Debug/symbols"
resource_root_dir="$GAME_ROOT_DIR/home/zeus/projects/pong-source/Debug/resources"
component_library_dir="$GAME_ROOT_DIR/home/zeus/projects/pong-source/Debug/src"
component_manifest_dir="$GAME_ROOT_DIR/home/zeus/projects/pong-source/Debug/manifests/default"
component_override_file="${GAME_MANIFEST_OVERRIDE:-/etc/pong/MANIFEST.override.json}"
log_root_dir="${GAME_LOG_ROOT_DIR:-/home/zeus/projects/pong-source/Debug/logs}"
crashdump_root_dir="${GAME_CRASHDUMP_ROOT_DIR:-/home/zeus/projects/pong-source/Debug/dumps}"
glog_options="${GAME_GLOG_OPTIONS:---max_log_size=10 --alsologtostderr --stop_logging_if_full_disk}"
contact_email_address="${GAME_CONTACT_EMAIL_ADDRESS:-}"


################################################################################
# Sources the implementation to run the executable.
################################################################################
source ${FUNAPI_DATA_DIR}/bash/launcher-common.sh