//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: funapi/network/fun_message.proto
namespace funapi.network.fun_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunMessage")]
  public partial class FunMessage : global::ProtoBuf.IExtensible
  {
    public FunMessage() {}
    
    private string _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sid
    {
      get { return _sid?? ""; }
      set { _sid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sidSpecified
    {
      get { return this._sid != null; }
      set { if (value == (this._sid== null)) this._sid = value ? this.sid : (string)null; }
    }
    private bool ShouldSerializesid() { return sidSpecified; }
    private void Resetsid() { sidSpecified = false; }
    
    private string _msgtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msgtype
    {
      get { return _msgtype?? ""; }
      set { _msgtype = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgtypeSpecified
    {
      get { return this._msgtype != null; }
      set { if (value == (this._msgtype== null)) this._msgtype = value ? this.msgtype : (string)null; }
    }
    private bool ShouldSerializemsgtype() { return msgtypeSpecified; }
    private void Resetmsgtype() { msgtypeSpecified = false; }
    
    private uint? _seq;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seq
    {
      get { return _seq?? default(uint); }
      set { _seq = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool seqSpecified
    {
      get { return this._seq != null; }
      set { if (value == (this._seq== null)) this._seq = value ? this.seq : (uint?)null; }
    }
    private bool ShouldSerializeseq() { return seqSpecified; }
    private void Resetseq() { seqSpecified = false; }
    
    private uint? _ack;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ack
    {
      get { return _ack?? default(uint); }
      set { _ack = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ackSpecified
    {
      get { return this._ack != null; }
      set { if (value == (this._ack== null)) this._ack = value ? this.ack : (uint?)null; }
    }
    private bool ShouldSerializeack() { return ackSpecified; }
    private void Resetack() { ackSpecified = false; }
    
    private bool? _urgent;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"urgent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool urgent
    {
      get { return _urgent?? default(bool); }
      set { _urgent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool urgentSpecified
    {
      get { return this._urgent != null; }
      set { if (value == (this._urgent== null)) this._urgent = value ? this.urgent : (bool?)null; }
    }
    private bool ShouldSerializeurgent() { return urgentSpecified; }
    private void Reseturgent() { urgentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: funapi/network/ping_message.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
namespace funapi.network.ping_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunPingMessage")]
  public partial class FunPingMessage : global::ProtoBuf.IExtensible
  {
    public FunPingMessage() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data?? null; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return this._data != null; }
      set { if (value == (this._data== null)) this._data = value ? this.data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: funapi/management/maintenance_message.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
namespace funapi.management.maintenance_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaintenanceMessage")]
  public partial class MaintenanceMessage : global::ProtoBuf.IExtensible
  {
    public MaintenanceMessage() {}
    
    private string _date_start;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"date_start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string date_start
    {
      get { return _date_start?? ""; }
      set { _date_start = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool date_startSpecified
    {
      get { return this._date_start != null; }
      set { if (value == (this._date_start== null)) this._date_start = value ? this.date_start : (string)null; }
    }
    private bool ShouldSerializedate_start() { return date_startSpecified; }
    private void Resetdate_start() { date_startSpecified = false; }
    
    private string _date_end;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"date_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string date_end
    {
      get { return _date_end?? ""; }
      set { _date_end = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool date_endSpecified
    {
      get { return this._date_end != null; }
      set { if (value == (this._date_end== null)) this._date_end = value ? this.date_end : (string)null; }
    }
    private bool ShouldSerializedate_end() { return date_endSpecified; }
    private void Resetdate_end() { date_endSpecified = false; }
    
    private string _messages;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string messages
    {
      get { return _messages?? ""; }
      set { _messages = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messagesSpecified
    {
      get { return this._messages != null; }
      set { if (value == (this._messages== null)) this._messages = value ? this.messages : (string)null; }
    }
    private bool ShouldSerializemessages() { return messagesSpecified; }
    private void Resetmessages() { messagesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: funapi/service/multicast_message.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
namespace funapi.service.multicast_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunMulticastChannelListMessage")]
  public partial class FunMulticastChannelListMessage : global::ProtoBuf.IExtensible
  {
    public FunMulticastChannelListMessage() {}
    
    private string _channel_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel_name
    {
      get { return _channel_name; }
      set { _channel_name = value; }
    }
    private uint? _num_members;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num_members", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num_members
    {
      get { return _num_members?? default(uint); }
      set { _num_members = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool num_membersSpecified
    {
      get { return this._num_members != null; }
      set { if (value == (this._num_members== null)) this._num_members = value ? this.num_members : (uint?)null; }
    }
    private bool ShouldSerializenum_members() { return num_membersSpecified; }
    private void Resetnum_members() { num_membersSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunMulticastMessage")]
  public partial class FunMulticastMessage : global::ProtoBuf.IExtensible
  {
    public FunMulticastMessage() {}
    
    private string _channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel
    {
      get { return _channel?? ""; }
      set { _channel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool channelSpecified
    {
      get { return this._channel != null; }
      set { if (value == (this._channel== null)) this._channel = value ? this.channel : (string)null; }
    }
    private bool ShouldSerializechannel() { return channelSpecified; }
    private void Resetchannel() { channelSpecified = false; }
    
    private bool? _join;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"join", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool join
    {
      get { return _join?? default(bool); }
      set { _join = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool joinSpecified
    {
      get { return this._join != null; }
      set { if (value == (this._join== null)) this._join = value ? this.join : (bool?)null; }
    }
    private bool ShouldSerializejoin() { return joinSpecified; }
    private void Resetjoin() { joinSpecified = false; }
    
    private bool? _leave;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leave", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool leave
    {
      get { return _leave?? default(bool); }
      set { _leave = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leaveSpecified
    {
      get { return this._leave != null; }
      set { if (value == (this._leave== null)) this._leave = value ? this.leave : (bool?)null; }
    }
    private bool ShouldSerializeleave() { return leaveSpecified; }
    private void Resetleave() { leaveSpecified = false; }
    
    private bool? _bounce;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bounce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bounce
    {
      get { return _bounce?? default(bool); }
      set { _bounce = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bounceSpecified
    {
      get { return this._bounce != null; }
      set { if (value == (this._bounce== null)) this._bounce = value ? this.bounce : (bool?)null; }
    }
    private bool ShouldSerializebounce() { return bounceSpecified; }
    private void Resetbounce() { bounceSpecified = false; }
    
    private string _sender;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender
    {
      get { return _sender?? ""; }
      set { _sender = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool senderSpecified
    {
      get { return this._sender != null; }
      set { if (value == (this._sender== null)) this._sender = value ? this.sender : (string)null; }
    }
    private bool ShouldSerializesender() { return senderSpecified; }
    private void Resetsender() { senderSpecified = false; }
    
    private FunMulticastMessage.ErrorCode? _error_code;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FunMulticastMessage.ErrorCode error_code
    {
      get { return _error_code?? FunMulticastMessage.ErrorCode.EC_ALREADY_JOINED; }
      set { _error_code = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool error_codeSpecified
    {
      get { return this._error_code != null; }
      set { if (value == (this._error_code== null)) this._error_code = value ? this.error_code : (FunMulticastMessage.ErrorCode?)null; }
    }
    private bool ShouldSerializeerror_code() { return error_codeSpecified; }
    private void Reseterror_code() { error_codeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<FunMulticastChannelListMessage> _channels = new global::System.Collections.Generic.List<FunMulticastChannelListMessage>();
    [global::ProtoBuf.ProtoMember(7, Name=@"channels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FunMulticastChannelListMessage> channels
    {
      get { return _channels; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EC_ALREADY_JOINED", Value=1)]
      EC_ALREADY_JOINED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EC_ALREADY_LEFT", Value=2)]
      EC_ALREADY_LEFT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EC_FULL_MEMBER", Value=3)]
      EC_FULL_MEMBER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EC_CLOSED", Value=4)]
      EC_CLOSED = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunChatMessage")]
  public partial class FunChatMessage : global::ProtoBuf.IExtensible
  {
    public FunChatMessage() {}
    
    private string _text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text?? ""; }
      set { _text = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool textSpecified
    {
      get { return this._text != null; }
      set { if (value == (this._text== null)) this._text = value ? this.text : (string)null; }
    }
    private bool ShouldSerializetext() { return textSpecified; }
    private void Resettext() { textSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: pong_messages.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
// Note: requires additional types generated from: funapi/service/multicast_message.proto
namespace pong_messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufEchoMessage")]
  public partial class PbufEchoMessage : global::ProtoBuf.IExtensible
  {
    public PbufEchoMessage() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufAnotherMessage")]
  public partial class PbufAnotherMessage : global::ProtoBuf.IExtensible
  {
    public PbufAnotherMessage() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg?? ""; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (string)null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufHelloMessage")]
  public partial class PbufHelloMessage : global::ProtoBuf.IExtensible
  {
    public PbufHelloMessage() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message?? ""; }
      set { _message = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageSpecified
    {
      get { return this._message != null; }
      set { if (value == (this._message== null)) this._message = value ? this.message : (string)null; }
    }
    private bool ShouldSerializemessage() { return messageSpecified; }
    private void Resetmessage() { messageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}