# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: funapi/distribution/fun_rpc_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='funapi/distribution/fun_rpc_message.proto',
  package='',
  serialized_pb='\n)funapi/distribution/fun_rpc_message.proto\"D\n\rFunRpcMessage\x12\x0e\n\x06sender\x18\x01 \x02(\x0c\x12\x0b\n\x03xid\x18\x02 \x02(\x0c\x12\x0c\n\x04type\x18\x03 \x02(\t*\x08\x08\x08\x10\x80\x80\x80\x80\x02\"\"\n\x12\x46unRpcErrorMessage\x12\x0c\n\x04what\x18\x01 \x02(\t\"!\n\x11\x46unRpcPingMessage\x12\x0c\n\x04text\x18\x01 \x02(\t\"\x15\n\x13\x46unRpcObjectMessage:2\n\x05\x65rror\x12\x0e.FunRpcMessage\x18\x08 \x01(\x0b\x32\x13.FunRpcErrorMessage:0\n\x04ping\x12\x0e.FunRpcMessage\x18\t \x01(\x0b\x32\x12.FunRpcPingMessage')


ERROR_FIELD_NUMBER = 8
error = _descriptor.FieldDescriptor(
  name='error', full_name='error', index=0,
  number=8, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
PING_FIELD_NUMBER = 9
ping = _descriptor.FieldDescriptor(
  name='ping', full_name='ping', index=1,
  number=9, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_FUNRPCMESSAGE = _descriptor.Descriptor(
  name='FunRpcMessage',
  full_name='FunRpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='FunRpcMessage.sender', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xid', full_name='FunRpcMessage.xid', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='FunRpcMessage.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(8, 536870912), ],
  serialized_start=45,
  serialized_end=113,
)


_FUNRPCERRORMESSAGE = _descriptor.Descriptor(
  name='FunRpcErrorMessage',
  full_name='FunRpcErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='what', full_name='FunRpcErrorMessage.what', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=149,
)


_FUNRPCPINGMESSAGE = _descriptor.Descriptor(
  name='FunRpcPingMessage',
  full_name='FunRpcPingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='FunRpcPingMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=184,
)


_FUNRPCOBJECTMESSAGE = _descriptor.Descriptor(
  name='FunRpcObjectMessage',
  full_name='FunRpcObjectMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['FunRpcMessage'] = _FUNRPCMESSAGE
DESCRIPTOR.message_types_by_name['FunRpcErrorMessage'] = _FUNRPCERRORMESSAGE
DESCRIPTOR.message_types_by_name['FunRpcPingMessage'] = _FUNRPCPINGMESSAGE
DESCRIPTOR.message_types_by_name['FunRpcObjectMessage'] = _FUNRPCOBJECTMESSAGE

class FunRpcMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNRPCMESSAGE

  # @@protoc_insertion_point(class_scope:FunRpcMessage)

class FunRpcErrorMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNRPCERRORMESSAGE

  # @@protoc_insertion_point(class_scope:FunRpcErrorMessage)

class FunRpcPingMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNRPCPINGMESSAGE

  # @@protoc_insertion_point(class_scope:FunRpcPingMessage)

class FunRpcObjectMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNRPCOBJECTMESSAGE

  # @@protoc_insertion_point(class_scope:FunRpcObjectMessage)

error.message_type = _FUNRPCERRORMESSAGE
FunRpcMessage.RegisterExtension(error)
ping.message_type = _FUNRPCPINGMESSAGE
FunRpcMessage.RegisterExtension(ping)

# @@protoc_insertion_point(module_scope)
