# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: funapi/network/ping_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import funapi.network.fun_message_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='funapi/network/ping_message.proto',
  package='',
  serialized_pb='\n!funapi/network/ping_message.proto\x1a funapi/network/fun_message.proto\"1\n\x0e\x46unPingMessage\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c:-\n\x07\x63s_ping\x12\x0b.FunMessage\x18\t \x01(\x0b\x32\x0f.FunPingMessage')


CS_PING_FIELD_NUMBER = 9
cs_ping = _descriptor.FieldDescriptor(
  name='cs_ping', full_name='cs_ping', index=0,
  number=9, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_FUNPINGMESSAGE = _descriptor.Descriptor(
  name='FunPingMessage',
  full_name='FunPingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FunPingMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='FunPingMessage.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['FunPingMessage'] = _FUNPINGMESSAGE

class FunPingMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNPINGMESSAGE

  # @@protoc_insertion_point(class_scope:FunPingMessage)

cs_ping.message_type = _FUNPINGMESSAGE
funapi.network.fun_message_pb2.FunMessage.RegisterExtension(cs_ping)

# @@protoc_insertion_point(module_scope)
