# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: funapi/service/multicast_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import funapi.network.fun_message_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='funapi/service/multicast_message.proto',
  package='',
  serialized_pb='\n&funapi/service/multicast_message.proto\x1a funapi/network/fun_message.proto\"K\n\x1e\x46unMulticastChannelListMessage\x12\x14\n\x0c\x63hannel_name\x18\x01 \x02(\t\x12\x13\n\x0bnum_members\x18\x02 \x01(\r\"\xb0\x02\n\x13\x46unMulticastMessage\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0c\n\x04join\x18\x02 \x01(\x08\x12\r\n\x05leave\x18\x03 \x01(\x08\x12\x0e\n\x06\x62ounce\x18\x04 \x01(\x08\x12\x0e\n\x06sender\x18\x05 \x01(\t\x12\x32\n\nerror_code\x18\x06 \x01(\x0e\x32\x1e.FunMulticastMessage.ErrorCode\x12\x31\n\x08\x63hannels\x18\x07 \x03(\x0b\x32\x1f.FunMulticastChannelListMessage\"Z\n\tErrorCode\x12\x15\n\x11\x45\x43_ALREADY_JOINED\x10\x01\x12\x13\n\x0f\x45\x43_ALREADY_LEFT\x10\x02\x12\x12\n\x0e\x45\x43_FULL_MEMBER\x10\x03\x12\r\n\tEC_CLOSED\x10\x04*\x08\x08\x08\x10\x80\x80\x80\x80\x02\"\x1e\n\x0e\x46unChatMessage\x12\x0c\n\x04text\x18\x01 \x01(\t:3\n\x04\x63hat\x12\x14.FunMulticastMessage\x18\x08 \x01(\x0b\x32\x0f.FunChatMessage:4\n\tmulticast\x12\x0b.FunMessage\x18\x08 \x01(\x0b\x32\x14.FunMulticastMessage')


CHAT_FIELD_NUMBER = 8
chat = _descriptor.FieldDescriptor(
  name='chat', full_name='chat', index=0,
  number=8, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MULTICAST_FIELD_NUMBER = 8
multicast = _descriptor.FieldDescriptor(
  name='multicast', full_name='multicast', index=1,
  number=8, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_FUNMULTICASTMESSAGE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='FunMulticastMessage.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EC_ALREADY_JOINED', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EC_ALREADY_LEFT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EC_FULL_MEMBER', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EC_CLOSED', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=358,
  serialized_end=448,
)


_FUNMULTICASTCHANNELLISTMESSAGE = _descriptor.Descriptor(
  name='FunMulticastChannelListMessage',
  full_name='FunMulticastChannelListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='FunMulticastChannelListMessage.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_members', full_name='FunMulticastChannelListMessage.num_members', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=151,
)


_FUNMULTICASTMESSAGE = _descriptor.Descriptor(
  name='FunMulticastMessage',
  full_name='FunMulticastMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='FunMulticastMessage.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='join', full_name='FunMulticastMessage.join', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leave', full_name='FunMulticastMessage.leave', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bounce', full_name='FunMulticastMessage.bounce', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='FunMulticastMessage.sender', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='FunMulticastMessage.error_code', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='FunMulticastMessage.channels', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FUNMULTICASTMESSAGE_ERRORCODE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(8, 536870912), ],
  serialized_start=154,
  serialized_end=458,
)


_FUNCHATMESSAGE = _descriptor.Descriptor(
  name='FunChatMessage',
  full_name='FunChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='FunChatMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=460,
  serialized_end=490,
)

_FUNMULTICASTMESSAGE.fields_by_name['error_code'].enum_type = _FUNMULTICASTMESSAGE_ERRORCODE
_FUNMULTICASTMESSAGE.fields_by_name['channels'].message_type = _FUNMULTICASTCHANNELLISTMESSAGE
_FUNMULTICASTMESSAGE_ERRORCODE.containing_type = _FUNMULTICASTMESSAGE;
DESCRIPTOR.message_types_by_name['FunMulticastChannelListMessage'] = _FUNMULTICASTCHANNELLISTMESSAGE
DESCRIPTOR.message_types_by_name['FunMulticastMessage'] = _FUNMULTICASTMESSAGE
DESCRIPTOR.message_types_by_name['FunChatMessage'] = _FUNCHATMESSAGE

class FunMulticastChannelListMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNMULTICASTCHANNELLISTMESSAGE

  # @@protoc_insertion_point(class_scope:FunMulticastChannelListMessage)

class FunMulticastMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNMULTICASTMESSAGE

  # @@protoc_insertion_point(class_scope:FunMulticastMessage)

class FunChatMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FUNCHATMESSAGE

  # @@protoc_insertion_point(class_scope:FunChatMessage)

chat.message_type = _FUNCHATMESSAGE
FunMulticastMessage.RegisterExtension(chat)
multicast.message_type = _FUNMULTICASTMESSAGE
funapi.network.fun_message_pb2.FunMessage.RegisterExtension(multicast)

# @@protoc_insertion_point(module_scope)
