// Generated by the iFun Engine.
// DO NOT EDIT.

#ifndef ACTIVITY_LOGGER__HOME_ZEUS_PROJECTS_PONG_SOURCE_DEBUG_SRC_PONG_LOGGERS_H_
#define ACTIVITY_LOGGER__HOME_ZEUS_PROJECTS_PONG_SOURCE_DEBUG_SRC_PONG_LOGGERS_H_

#include <funapi.h>
#include <boost/date_time/posix_time/posix_time.hpp>


namespace logger {

using fun::string;

void SessionOpened(const string & arg_session_id, const WallClock::Value & arg_when);
void SessionClosed(const string & arg_session_id, const WallClock::Value & arg_when);
void PlayerLoggedIn(const string & arg_session_id, const string & arg_account_id, const WallClock::Value & arg_when);
}  // namespace logger

#endif  // ACTIVITY_LOGGER__HOME_ZEUS_PROJECTS_PONG_SOURCE_DEBUG_SRC_PONG_LOGGERS_H_
