# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pong_rpc_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import funapi.distribution.fun_rpc_message_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pong_rpc_messages.proto',
  package='',
  serialized_pb='\n\x17pong_rpc_messages.proto\x1a)funapi/distribution/fun_rpc_message.proto\"!\n\x0e\x45\x63hoRpcMessage\x12\x0f\n\x07message\x18\x01 \x01(\t:1\n\x08\x65\x63ho_rpc\x12\x0e.FunRpcMessage\x18  \x01(\x0b\x32\x0f.EchoRpcMessage')


ECHO_RPC_FIELD_NUMBER = 32
echo_rpc = _descriptor.FieldDescriptor(
  name='echo_rpc', full_name='echo_rpc', index=0,
  number=32, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ECHORPCMESSAGE = _descriptor.Descriptor(
  name='EchoRpcMessage',
  full_name='EchoRpcMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EchoRpcMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['EchoRpcMessage'] = _ECHORPCMESSAGE

class EchoRpcMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHORPCMESSAGE

  # @@protoc_insertion_point(class_scope:EchoRpcMessage)

echo_rpc.message_type = _ECHORPCMESSAGE
funapi.distribution.fun_rpc_message_pb2.FunRpcMessage.RegisterExtension(echo_rpc)

# @@protoc_insertion_point(module_scope)
