// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pong_rpc_messages.proto

#ifndef PROTOBUF_pong_5frpc_5fmessages_2eproto__INCLUDED
#define PROTOBUF_pong_5frpc_5fmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "funapi/distribution/fun_rpc_message.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pong_5frpc_5fmessages_2eproto();
void protobuf_AssignDesc_pong_5frpc_5fmessages_2eproto();
void protobuf_ShutdownFile_pong_5frpc_5fmessages_2eproto();

class EchoRpcMessage;

// ===================================================================

class EchoRpcMessage : public ::google::protobuf::Message {
 public:
  EchoRpcMessage();
  virtual ~EchoRpcMessage();

  EchoRpcMessage(const EchoRpcMessage& from);

  inline EchoRpcMessage& operator=(const EchoRpcMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EchoRpcMessage& default_instance();

  void Swap(EchoRpcMessage* other);

  // implements Message ----------------------------------------------

  EchoRpcMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EchoRpcMessage& from);
  void MergeFrom(const EchoRpcMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string message = 1;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 1;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:EchoRpcMessage)
 private:
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* message_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_pong_5frpc_5fmessages_2eproto();
  friend void protobuf_AssignDesc_pong_5frpc_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_pong_5frpc_5fmessages_2eproto();

  void InitAsDefaultInstance();
  static EchoRpcMessage* default_instance_;
};
// ===================================================================

static const int kEchoRpcFieldNumber = 32;
extern ::google::protobuf::internal::ExtensionIdentifier< ::FunRpcMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::EchoRpcMessage >, 11, false >
  echo_rpc;

// ===================================================================

// EchoRpcMessage

// optional string message = 1;
inline bool EchoRpcMessage::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EchoRpcMessage::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EchoRpcMessage::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EchoRpcMessage::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& EchoRpcMessage::message() const {
  return *message_;
}
inline void EchoRpcMessage::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void EchoRpcMessage::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void EchoRpcMessage::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EchoRpcMessage::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* EchoRpcMessage::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EchoRpcMessage::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pong_5frpc_5fmessages_2eproto__INCLUDED
