// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pong_messages.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pong_messages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PbufEchoMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbufEchoMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* PbufAnotherMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbufAnotherMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* PbufHelloMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbufHelloMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pong_5fmessages_2eproto() {
  protobuf_AddDesc_pong_5fmessages_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pong_messages.proto");
  GOOGLE_CHECK(file != NULL);
  PbufEchoMessage_descriptor_ = file->message_type(0);
  static const int PbufEchoMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufEchoMessage, msg_),
  };
  PbufEchoMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PbufEchoMessage_descriptor_,
      PbufEchoMessage::default_instance_,
      PbufEchoMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufEchoMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufEchoMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PbufEchoMessage));
  PbufAnotherMessage_descriptor_ = file->message_type(1);
  static const int PbufAnotherMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufAnotherMessage, msg_),
  };
  PbufAnotherMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PbufAnotherMessage_descriptor_,
      PbufAnotherMessage::default_instance_,
      PbufAnotherMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufAnotherMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufAnotherMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PbufAnotherMessage));
  PbufHelloMessage_descriptor_ = file->message_type(2);
  static const int PbufHelloMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufHelloMessage, message_),
  };
  PbufHelloMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PbufHelloMessage_descriptor_,
      PbufHelloMessage::default_instance_,
      PbufHelloMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufHelloMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbufHelloMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PbufHelloMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pong_5fmessages_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PbufEchoMessage_descriptor_, &PbufEchoMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PbufAnotherMessage_descriptor_, &PbufAnotherMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PbufHelloMessage_descriptor_, &PbufHelloMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pong_5fmessages_2eproto() {
  delete PbufEchoMessage::default_instance_;
  delete PbufEchoMessage_reflection_;
  delete PbufAnotherMessage::default_instance_;
  delete PbufAnotherMessage_reflection_;
  delete PbufHelloMessage::default_instance_;
  delete PbufHelloMessage_reflection_;
}

void protobuf_AddDesc_pong_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_funapi_2fnetwork_2ffun_5fmessage_2eproto();
  ::protobuf_AddDesc_funapi_2fservice_2fmulticast_5fmessage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023pong_messages.proto\032 funapi/network/fu"
    "n_message.proto\032&funapi/service/multicas"
    "t_message.proto\"\036\n\017PbufEchoMessage\022\013\n\003ms"
    "g\030\001 \002(\t\"!\n\022PbufAnotherMessage\022\013\n\003msg\030\001 \001"
    "(\t\"#\n\020PbufHelloMessage\022\017\n\007message\030\001 \001(\t:"
    "0\n\tpbuf_echo\022\013.FunMessage\030\020 \001(\0132\020.PbufEc"
    "hoMessage:6\n\014pbuf_another\022\013.FunMessage\030\021"
    " \001(\0132\023.PbufAnotherMessage:;\n\npbuf_hello\022"
    "\024.FunMulticastMessage\030\t \001(\0132\021.PbufHelloM"
    "essage", 366);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pong_messages.proto", &protobuf_RegisterTypes);
  PbufEchoMessage::default_instance_ = new PbufEchoMessage();
  PbufAnotherMessage::default_instance_ = new PbufAnotherMessage();
  PbufHelloMessage::default_instance_ = new PbufHelloMessage();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::FunMessage::default_instance(),
    16, 11, false, false,
    &::PbufEchoMessage::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::FunMessage::default_instance(),
    17, 11, false, false,
    &::PbufAnotherMessage::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::FunMulticastMessage::default_instance(),
    9, 11, false, false,
    &::PbufHelloMessage::default_instance());
  PbufEchoMessage::default_instance_->InitAsDefaultInstance();
  PbufAnotherMessage::default_instance_->InitAsDefaultInstance();
  PbufHelloMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pong_5fmessages_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pong_5fmessages_2eproto {
  StaticDescriptorInitializer_pong_5fmessages_2eproto() {
    protobuf_AddDesc_pong_5fmessages_2eproto();
  }
} static_descriptor_initializer_pong_5fmessages_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PbufEchoMessage::kMsgFieldNumber;
#endif  // !_MSC_VER

PbufEchoMessage::PbufEchoMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PbufEchoMessage::InitAsDefaultInstance() {
}

PbufEchoMessage::PbufEchoMessage(const PbufEchoMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PbufEchoMessage::SharedCtor() {
  _cached_size_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbufEchoMessage::~PbufEchoMessage() {
  SharedDtor();
}

void PbufEchoMessage::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void PbufEchoMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbufEchoMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbufEchoMessage_descriptor_;
}

const PbufEchoMessage& PbufEchoMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pong_5fmessages_2eproto();
  return *default_instance_;
}

PbufEchoMessage* PbufEchoMessage::default_instance_ = NULL;

PbufEchoMessage* PbufEchoMessage::New() const {
  return new PbufEchoMessage;
}

void PbufEchoMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msg()) {
      if (msg_ != &::google::protobuf::internal::kEmptyString) {
        msg_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PbufEchoMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string msg = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PbufEchoMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PbufEchoMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PbufEchoMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string msg = 1;
    if (has_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbufEchoMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PbufEchoMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PbufEchoMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PbufEchoMessage::MergeFrom(const PbufEchoMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg()) {
      set_msg(from.msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PbufEchoMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbufEchoMessage::CopyFrom(const PbufEchoMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbufEchoMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void PbufEchoMessage::Swap(PbufEchoMessage* other) {
  if (other != this) {
    std::swap(msg_, other->msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PbufEchoMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbufEchoMessage_descriptor_;
  metadata.reflection = PbufEchoMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PbufAnotherMessage::kMsgFieldNumber;
#endif  // !_MSC_VER

PbufAnotherMessage::PbufAnotherMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PbufAnotherMessage::InitAsDefaultInstance() {
}

PbufAnotherMessage::PbufAnotherMessage(const PbufAnotherMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PbufAnotherMessage::SharedCtor() {
  _cached_size_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbufAnotherMessage::~PbufAnotherMessage() {
  SharedDtor();
}

void PbufAnotherMessage::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void PbufAnotherMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbufAnotherMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbufAnotherMessage_descriptor_;
}

const PbufAnotherMessage& PbufAnotherMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pong_5fmessages_2eproto();
  return *default_instance_;
}

PbufAnotherMessage* PbufAnotherMessage::default_instance_ = NULL;

PbufAnotherMessage* PbufAnotherMessage::New() const {
  return new PbufAnotherMessage;
}

void PbufAnotherMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msg()) {
      if (msg_ != &::google::protobuf::internal::kEmptyString) {
        msg_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PbufAnotherMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string msg = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PbufAnotherMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PbufAnotherMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PbufAnotherMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string msg = 1;
    if (has_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbufAnotherMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PbufAnotherMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PbufAnotherMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PbufAnotherMessage::MergeFrom(const PbufAnotherMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg()) {
      set_msg(from.msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PbufAnotherMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbufAnotherMessage::CopyFrom(const PbufAnotherMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbufAnotherMessage::IsInitialized() const {

  return true;
}

void PbufAnotherMessage::Swap(PbufAnotherMessage* other) {
  if (other != this) {
    std::swap(msg_, other->msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PbufAnotherMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbufAnotherMessage_descriptor_;
  metadata.reflection = PbufAnotherMessage_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PbufHelloMessage::kMessageFieldNumber;
#endif  // !_MSC_VER

PbufHelloMessage::PbufHelloMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PbufHelloMessage::InitAsDefaultInstance() {
}

PbufHelloMessage::PbufHelloMessage(const PbufHelloMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PbufHelloMessage::SharedCtor() {
  _cached_size_ = 0;
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbufHelloMessage::~PbufHelloMessage() {
  SharedDtor();
}

void PbufHelloMessage::SharedDtor() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (this != default_instance_) {
  }
}

void PbufHelloMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbufHelloMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbufHelloMessage_descriptor_;
}

const PbufHelloMessage& PbufHelloMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pong_5fmessages_2eproto();
  return *default_instance_;
}

PbufHelloMessage* PbufHelloMessage::default_instance_ = NULL;

PbufHelloMessage* PbufHelloMessage::New() const {
  return new PbufHelloMessage;
}

void PbufHelloMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::kEmptyString) {
        message_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PbufHelloMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string message = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PbufHelloMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string message = 1;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->message(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PbufHelloMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string message = 1;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PbufHelloMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string message = 1;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->message());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbufHelloMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PbufHelloMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PbufHelloMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PbufHelloMessage::MergeFrom(const PbufHelloMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_message()) {
      set_message(from.message());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PbufHelloMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbufHelloMessage::CopyFrom(const PbufHelloMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbufHelloMessage::IsInitialized() const {

  return true;
}

void PbufHelloMessage::Swap(PbufHelloMessage* other) {
  if (other != this) {
    std::swap(message_, other->message_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PbufHelloMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbufHelloMessage_descriptor_;
  metadata.reflection = PbufHelloMessage_reflection_;
  return metadata;
}

::google::protobuf::internal::ExtensionIdentifier< ::FunMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::PbufEchoMessage >, 11, false >
  pbuf_echo(kPbufEchoFieldNumber, ::PbufEchoMessage::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::FunMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::PbufAnotherMessage >, 11, false >
  pbuf_another(kPbufAnotherFieldNumber, ::PbufAnotherMessage::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::FunMulticastMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::PbufHelloMessage >, 11, false >
  pbuf_hello(kPbufHelloFieldNumber, ::PbufHelloMessage::default_instance());

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
